<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"
%><%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions"
%><%@ taglib prefix="bs" tagdir="/WEB-INF/tags"
%><%@ taglib prefix="t" tagdir="/WEB-INF/tags/tags"
%><%@ taglib prefix="authz" tagdir="/WEB-INF/tags/authz"
%><jsp:useBean id="buildPromotion" scope="request" type="jetbrains.buildServer.serverSide.BuildPromotionEx"
/><jsp:useBean id="favorite" scope="request" type="java.lang.Boolean"
/><%@ taglib prefix="afn" uri="/WEB-INF/functions/authz"
%><c:if test="${afn:permissionGrantedForProjectWithId(buildPromotion.projectId, 'TAG_BUILD') && afn:permissionGrantedGlobally('CHANGE_OWN_PROFILE')}"
><t:favoriteBuildInner buildPromotion="${buildPromotion}"
                       favorite="${favorite}"
                       showActionText="${showActionText}"
                       showOnlyIfFavorite="${showOnlyIfFavorite}"
                       showDescription="${showDescription}"
                       cssClass="${cssClass}"
                       removeCssClass="${removeCssClass}"/></c:if>